### ISSUE TITLE
Generalization question.

### ISSUE THREAD

**Issue by kaijieshi7** [ToruOwO/hato#2]
Hi. Thank you for this interesting paper.
There are no generalization results in the paper.
Can you just briefly talk about the generalization results?
Thank you very much.

**Comment by ToruOwO** [comment]
Hi! We did not formally study generalization, and our empirical observations match existing results: the policy is able to generalize to environment settings that have been randomized during the data collection process, e.g. different object poses (as can be seen in [this](https://twitter.com/ToruO_O/status/1783896742603485523) tweet).
