### ISSUE TITLE
How much computing power is required at least? 

### ISSUE THREAD

**Issue by RIP4KOBE** [ToruOwO/hato#4]
Hello, Could you introduce your hardware setup, for example, how many GPUs you use or how much computing power is required? Thanks!

**Comment by ToruOwO** [comment]
For training, we used a mix of GPU types (e.g. A100, 4090, 3080). Each policy was trained on a single GPU; training typically takes 10~20hrs depending on the data size.

**Comment by aliyah-smith** [comment]
How many epochs did you train for? Thanks!

**Comment by ToruOwO** [comment]
Hi @aliyah-smith -- we train for 300 epochs, as defined in the [default](https://github.com/ToruOwO/hato/blob/main/learning/dp/pipeline.py#L747) config.
