### ISSUE TITLE
Camera Utilization Problem

### ISSUE THREAD

**Issue by RIP4KOBE** [ToruOwO/hato#5]
Thanks for your impressive work!

May I ask why only base_rgb images were used in the pipeline.py? Why was the data from the other two wrist cameras not used?
![image](https://github.com/user-attachments/assets/c41889d3-ad93-42d0-978b-4b07ccf5b325)

**Comment by ToruOwO** [comment]
Thanks for your interest! We do use from images from all three cameras, as specified by the `camera_indices` argument! You can check out more details from this line: https://github.com/ToruOwO/hato/blob/main/learning/dp/pipeline.py#L67
