### ISSUE TITLE
Hardware Component

### ISSUE THREAD

**Issue by JayceWen** [ToruOwO/hato#6]
Hello, your work is very fantastic. And l wll appreciate that if you can share me where to buy the T-shape base?
<img width="392" alt="image" src="https://github.com/user-attachments/assets/779e46c5-f2f3-4b3a-9cce-48b4cd3cae77">

**Comment by ToruOwO** [comment]
Hi, thanks for the interest! In fact, base is not a commercial product available for sale; we designed it on our own and ordered the base from an industrial manufacturer [MotionAI](https://ai.motion.com/). Please feel free to send me an email if you'd like a copy of the design file :)
